// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Car;
//
//    var car = Car.FromJson(jsonString);

namespace Car
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Carma
    {
        [JsonProperty("greeting")]
        public string Greeting { get; set; }

        [JsonProperty("instructions")]
        public string[] Instructions { get; set; }
    }

    public partial class Carma
    {
        public static Carma FromJson(string json) => JsonConvert.DeserializeObject<Carma>(json, Car.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Carma self) => JsonConvert.SerializeObject(self, Car.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}